# Generated by Django 3.1.4 on 2021-05-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Birthday', models.DateField()),
                ('Phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('close_friend', models.BooleanField()),
            ],
        ),
    ]
