# Generated by Django 3.1.4 on 2021-05-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningdatabase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Done', models.BooleanField()),
                ('Date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='friends',
        ),
    ]
